---
kind: pipeline
type: docker
name: default

trigger:
  branch:
    - master

steps:
  - name: install
    image: node:16
    commands:
      - node -v
      - npm -v
      - yarn --version
      - yarn install

  - name: production
    image: node:16
    volumes:
      - name: env-volume
        path: ${DRONE_WORKSPACE}/.env
    commands:
      - yarn production

volumes:
  - name: env-volume
    host:
      path: /home/harlos/projects/cron-reminder-dc-bot/.env
