---
kind: pipeline
type: docker
name: default

trigger:
  branch:
    - master

steps:
  - name: install
    image: node:16
    commands:
      - node -v
      - npm -v
      - yarn --version
      - yarn install

  - name: production
    image: node:16
    environment:
      BOT_TOKEN:
        from_secret: BOT_TOKEN
      CRON_CHANNEL_ID:
        from_secret: CRON_CHANNEL_ID
      REMINDER_CHANNEL_ID:
        from_secret: REMINDER_CHANNEL_ID
    commands:
      - yarn production

