name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t harlos/cron-reminder-dc-bot .

    - name: Run Docker container
      run: docker run -d harlos/cron-reminder-dc-bot
